# Generated by Django 4.1.7 on 2023-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tickerdata_ticker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdata',
            name='Ticker_name',
            field=models.CharField(default='RELIANCE.NS', max_length=200),
        ),
    ]
