# Generated by Django 4.1.7 on 2023-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdata_alter_tickerdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
