# Generated by Django 4.1.7 on 2023-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tickerdata_ticker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cprice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='Date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='Volume',
            field=models.IntegerField(),
        ),
    ]
