# Generated by Django 4.1.7 on 2023-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_logindata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
