# Generated by Django 4.1.7 on 2023-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_portfolio_name_alter_portfolio_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.AddField(
            model_name='logindata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=7, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='username',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
