# Generated by Django 4.1.7 on 2023-03-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_portfolio_id_logindata_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
