# Generated by Django 4.1.7 on 2023-03-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
