# Generated by Django 4.1.7 on 2023-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_logindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='balance',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
