# Generated by Django 4.1.7 on 2023-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userdata_balance_userdata_loss_userdata_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
        ),
    ]
