# Generated by Django 4.1.7 on 2023-03-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_buylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylist',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buylist',
            name='q',
            field=models.IntegerField(),
        ),
    ]
