# Generated by Django 4.1.7 on 2023-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_buylist_price_alter_buylist_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylist',
            name='q',
            field=models.CharField(max_length=200),
        ),
    ]
