# Generated by Django 4.1.7 on 2023-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_buylist_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylist',
            name='username',
            field=models.CharField(default='username', max_length=200),
            preserve_default=False,
        ),
    ]
