# Generated by Django 4.1.7 on 2023-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='Ticker',
            new_name='ticker_name',
        ),
    ]
