# Generated by Django 4.1.7 on 2023-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userdata_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerdata',
            name='Ticker_name',
        ),
    ]
